# Generated by Django 4.1 on 2024-04-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_module", "0002_alter_producttable_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttable",
            name="count",
            field=models.IntegerField(verbose_name="Nombre de produits"),
        ),
        migrations.AlterField(
            model_name="producttable",
            name="is_active",
            field=models.BooleanField(verbose_name="inventaire"),
        ),
        migrations.AlterField(
            model_name="producttable",
            name="price",
            field=models.IntegerField(verbose_name="prix du produit"),
        ),
        migrations.AlterField(
            model_name="producttable",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Nom du produit"),
        ),
    ]
